#
# This file controls standalone local override modules.
# Only modules from policy/modules/local are considered here.
#
# Local modules are compiled and loaded separately from the base policy:
#   make local-modules
#   make install-local
#   make load-local
#
# Valid states:
#   module - build/install/load this local override module
#   off    - ignore this local module
#
# Local modules should be named local_<something>.
#

local_test = module
local_accountsd = module
local_devicekit_power = module
local_pcscd = module
local_plymouth = module
local_switcheroo = module
local_systemd_pcrphase = module
local_syslogd = module
local_systemd_tmpfiles = module
local_zfs = module
local_sysadm = off
local_systemd_hostnamed = module
local_systemd_locale = module
local_systemd_logind = module
local_systemd_machined = module
local_systemd_sessions = module
local_systemd_user_runtime_dir = module
