#
# This file controls standalone local override modules.
# Only modules from policy/modules/local are considered here.
#
# Local modules are compiled and loaded separately from the base policy:
#   make modules-local
#   make install-local
#   make load-local
#
# Valid states:
#   module - build/install/load this local override module
#   off    - ignore this local module
#
# Local modules should be named local_<something>.
#

local_test = module
local_accountsd = module
local_auditadm = module
local_backlighthelper = module
local_bluetooth = module
local_bird = module
local_chargethresholdhelper = module
local_chromium = module
local_clipboard = module
local_code = module
local_command_not_found = module
local_cryptsetup = module
local_dante = module
local_dbus = module
local_discover_notifier = module
local_discretegpuhelper = module
local_devicekit_power = module
local_dnsmasq = module
local_dolphin = module
local_evince = module
local_evolution = module
local_fsadm = module
local_fwupd = module
local_getty = module
local_gvfs = module
local_git = module
local_gpg = module
local_gnome = module
local_gkrellm = module
local_gstpluginscanner = module
local_ifconfig = module
local_ipsec = module
local_kded_smart = module
local_kdeconnect = module
local_keepassxc = module
local_kioworker = module
local_konsole = module
local_kscreenlocker = module
local_lvm = module
local_mozilla = module
local_lowmemorymonitor = module
local_mplayer = module
local_networkmanager = module
local_openvpn = module
local_pcscd = module
local_pipewire = module
local_plymouth = module
local_powerprofiles = module
local_powerdevil = module
local_qtwebengine = module
local_rsibreak = module
local_safeeyes = module
local_secadm = module
local_spectacle = module
local_ssh = module
local_switcheroo = module
local_sudo = module
local_staff = module
local_staff_wm = module
local_staff_systemd = module
local_svirt = module
local_systemd_pcrphase = module
local_syslogd = module
local_systemd_tmpfiles = module
local_zfs = module
local_sysadm = off
local_systemd_hostnamed = module
local_systemd_locale = module
local_systemd_logind = module
local_systemd_machined = module
local_systemd_sessions = module
local_systemd = module
local_systemd_user_runtime_dir = module
local_thunderbird = module
local_tpm2_pkcs11 = module
local_user = module
local_userdomain = module
local_utempter = module
local_usbguard = module
local_virt = module
local_virt_leaseshelper = module
local_virtlogd = module
local_wireplumber = module
local_xdg_document_portal = module
local_xwayland = module
local_zotero = module
